### ISSUE TITLE
Elm formatting breaks file watching

### ISSUE THREAD

**Issue by mikolajpp** [ElmCast/elm-vim#178] opened 2019-03-05 03:43 UTC
Enabling `g:elm_format_autosave` breaks file watchers of all kinds. It seems elm format is renaming the file, instead of overwriting it, as evidenced by inotify events.

**Comment by richyliu** [comment] 2019-03-06 00:01
Duplicate of #160

**Closed** 2019-03-07 03:05 UTC
